# 9.Pandas分组与聚合
设置索引

In [3]:
import pandas as pd
import numpy as np

a = pd.DataFrame({'a': range(7), 
                  'b': range(7, 0, -1), 
                  'c': ['one', 'one', 'one', 'two', 'two', 'two', 'two'],
                  'd': list('hjklmno')})
a

   a  b    c  d
0  0  7  one  h
1  1  6  one  j
2  2  5  one  k
3  3  4  two  l
4  4  3  two  m
5  5  2  two  n
6  6  1  two  o

In [4]:
c = a.copy()
print(c)
print('-' * 50)
a.index = list('abcdefg')                   # 更换a的索引
a.columns = list('ABCD')                    # 更换a的列名
print(a)

   a  b    c  d
0  0  7  one  h
1  1  6  one  j
2  2  5  one  k
3  3  4  two  l
4  4  3  two  m
5  5  2  two  n
6  6  1  two  o
--------------------------------------------------
   A  B    C  D
a  0  7  one  h
b  1  6  one  j
c  2  5  one  k
d  3  4  two  l
e  4  3  two  m
f  5  2  two  n
g  6  1  two  o

In [5]:
c.values.shape

(7, 4)

In [7]:
print(a)
print('-' * 50)
# 将列C提升为行索引；inplace=True：直接原地修改原数据a，不返回新DataFrame
a.set_index(['C'], inplace=True)
a

   A  B    C  D
a  0  7  one  h
b  1  6  one  j
c  2  5  one  k
d  3  4  two  l
e  4  3  two  m
f  5  2  two  n
g  6  1  two  o
--------------------------------------------------

     A  B  D
C
one  0  7  h
one  1  6  j
one  2  5  k
two  3  4  l
two  4  3  m
two  5  2  n
two  6  1  o

In [8]:
a.columns

Index(['A', 'B', 'D'], dtype='str')

In [9]:
a.index

Index(['one', 'one', 'one', 'two', 'two', 'two', 'two'], dtype='str', name='C')

# 时间序列

In [14]:
pd.date_range(start='20260801', end='20260901')             # 左闭右闭

DatetimeIndex(['2026-08-01', '2026-08-02', '2026-08-03', '2026-08-04',
               '2026-08-05', '2026-08-06', '2026-08-07', '2026-08-08',
               '2026-08-09', '2026-08-10', '2026-08-11', '2026-08-12',
               '2026-08-13', '2026-08-14', '2026-08-15', '2026-08-16',
               '2026-08-17', '2026-08-18', '2026-08-19', '2026-08-20',
               '2026-08-21', '2026-08-22', '2026-08-23', '2026-08-24',
               '2026-08-25', '2026-08-26', '2026-08-27', '2026-08-28',
               '2026-08-29', '2026-08-30', '2026-08-31', '2026-09-01'],
              dtype='datetime64[us]', freq='D')

In [13]:
# periods：指定生成多少个时间点    B：business day（工作日）
pd.date_range(start='20260804', periods=10, freq='B')

DatetimeIndex(['2026-08-04', '2026-08-05', '2026-08-06', '2026-08-07',
               '2026-08-10', '2026-08-11', '2026-08-12', '2026-08-13',
               '2026-08-14', '2026-08-17'],
              dtype='datetime64[us]', freq='B')

In [17]:
# periods：生成10个时间点；ME：month end
pd.date_range(start='20260804', periods=10, freq='ME')

DatetimeIndex(['2026-08-31', '2026-09-30', '2026-10-31', '2026-11-30',
               '2026-12-31', '2027-01-31', '2027-02-28', '2027-03-31',
               '2027-04-30', '2027-05-31'],
              dtype='datetime64[us]', freq='ME')

In [18]:
pd.date_range(start='20260804', periods=10, freq='MS')                      # month start

DatetimeIndex(['2026-09-01', '2026-10-01', '2026-11-01', '2026-12-01',
               '2027-01-01', '2027-02-01', '2027-03-01', '2027-04-01',
               '2027-05-01', '2027-06-01'],
              dtype='datetime64[us]', freq='MS')

In [19]:
pd.date_range(start='20260804', periods=10, freq='W')                       # W：week；拿每周的周日生成

DatetimeIndex(['2026-08-09', '2026-08-16', '2026-08-23', '2026-08-30',
               '2026-09-06', '2026-09-13', '2026-09-20', '2026-09-27',
               '2026-10-04', '2026-10-11'],
              dtype='datetime64[us]', freq='W-SUN')

In [21]:
s = pd.Series(['3/11/2000', '3/12/2000', '3/13/2000'] * 5)
print(len(s))
s

15

0     3/11/2000
1     3/12/2000
2     3/13/2000
3     3/11/2000
4     3/12/2000
5     3/13/2000
6     3/11/2000
7     3/12/2000
8     3/13/2000
9     3/11/2000
10    3/12/2000
11    3/13/2000
12    3/11/2000
13    3/12/2000
14    3/13/2000
dtype: str

In [22]:
pd.to_datetime(s)                   # to_datetime把字符串转为时间格式

0    2000-03-11
1    2000-03-12
2    2000-03-13
3    2000-03-11
4    2000-03-12
5    2000-03-13
6    2000-03-11
7    2000-03-12
8    2000-03-13
9    2000-03-11
10   2000-03-12
11   2000-03-13
12   2000-03-11
13   2000-03-12
14   2000-03-13
dtype: datetime64[us]

In [29]:
from matplotlib import pyplot as plt

# 把时间字符串转为时间类型设置为索引
df = pd.read_csv('./911.csv')
df['timeStamp'] = pd.to_datetime(df['timeStamp'])

temp_list = df['title'].str.split(':').tolist()                 # 二维列表
# 遍历temp_list里每一个元素i，取出i的第0号元素，拼成新列表
cate_list = [i[0] for i in temp_list]
# print(cate_list)
# print(np.array(cate_list).reshape((df.shape[0], 1)))
df['cate'] = pd.DataFrame(np.array(cate_list).reshape((df.shape[0], 1)))
print(type(df['cate']))                                         # <class 'pandas.Series'>
df.set_index('timeStamp', inplace=True)                         # 设置索引，时间戳，inplace=True表示在原df上修改
df.head()

<class 'pandas.Series'>

,lat,lng,desc,zip,title,twp,addr,e,cate
timeStamp,,,,,,,,,
2015-12-10 17:10:52,40.297876,-75.581294,REINDEER CT & DEAD END; NEW HANOVER; Station ...,19525.0,EMS: BACK PAINS/INJURY,NEW HANOVER,REINDEER CT & DEAD END,1,EMS
2015-12-10 17:29:21,40.258061,-75.264680,BRIAR PATH & WHITEMARSH LN; HATFIELD TOWNSHIP...,19446.0,EMS: DIABETIC EMERGENCY,HATFIELD TOWNSHIP,BRIAR PATH & WHITEMARSH LN,1,EMS
2015-12-10 14:39:21,40.121182,-75.351975,HAWS AVE; NORRISTOWN; 2015-12-10 @ 14:39:21-St...,19401.0,Fire: GAS-ODOR/LEAK,NORRISTOWN,HAWS AVE,1,Fire
2015-12-10 16:47:36,40.116153,-75.343513,AIRY ST & SWEDE ST; NORRISTOWN; Station 308A;...,19401.0,EMS: CARDIAC EMERGENCY,NORRISTOWN,AIRY ST & SWEDE ST,1,EMS
2015-12-10 16:56:52,40.251492,-75.603350,CHERRYWOOD CT & DEAD END; LOWER POTTSGROVE; S...,NaN,EMS: DIZZINESS,LOWER POTTSGROVE,CHERRYWOOD CT & DEAD END,1,EMS