# 处理重复数据

In [1]:
import pandas as pd
import numpy as np

In [3]:
df_obj = pd.DataFrame({'data1': ['a'] * 4 + ['b'] * 4, 
                       'data2': np.random.randint(0, 4, 8)})
print(df_obj)

  data1  data2
0     a      2
1     a      1
2     a      0
3     a      0
4     b      0
5     b      1
6     b      1
7     b      2

In [4]:
# 判断每一行是否是重复行，返回一个布尔Series  True：该行是重复行（前面已经出现过一摸一样的行）；False：该行是首次出现，不重复
print(df_obj.duplicated())

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7    False
dtype: bool

In [5]:
# 取出不重复的行
df_obj[~df_obj.duplicated()]

  data1  data2
0     a      2
1     a      1
2     a      0
4     b      0
5     b      1
7     b      2

In [6]:
# 按照某一列去重
print(df_obj.duplicated('data2'))

0    False
1    False
2    False
3     True
4     True
5     True
6     True
7     True
dtype: bool

In [7]:
df_obj1 = pd.DataFrame({'data1': [np.nan] * 4,
                        'data2': list('1234')})
df_obj1

   data1 data2
0    NaN     1
1    NaN     2
2    NaN     3
3    NaN     4

In [10]:
print(df_obj1.duplicated('data1'))
print(df_obj1.drop_duplicates('data1'))             # 后三行数据被删除

0    False
1     True
2     True
3     True
dtype: bool
   data1 data2
0    NaN     1

In [11]:
print(df_obj.drop_duplicates())                     # 删除重复行，左右数据全部相同的行才删除
print(df_obj.drop_duplicates('data2'))              # 特定列数据相同的行删除

  data1  data2
0     a      2
1     a      1
2     a      0
4     b      0
5     b      1
7     b      2
  data1  data2
0     a      2
1     a      1
2     a      0

In [12]:
# 如果要在原有的df上去重，需要加inplace=True
df_obj

  data1  data2
0     a      2
1     a      1
2     a      0
3     a      0
4     b      0
5     b      1
6     b      1
7     b      2

In [13]:
# map与applymap一样，但是map只能用于Series，applymap只能用于df
ser_obj = pd.Series(np.random.randint(0, 10, 10))       # Series用于map
print(ser_obj)

print(ser_obj.map(lambda x: x**2))

0    5
1    0
2    1
3    4
4    4
5    2
6    6
7    4
8    7
9    4
dtype: int64
0    25
1     0
2     1
3    16
4    16
5     4
6    36
7    16
8    49
9    16
dtype: int64

In [14]:
ser_obj = pd.Series(np.arange(10), index=range(3, 13))

# 这里是值 1 替换成 -100
print(ser_obj.replace(1, -100))
print('-' * 50)

# 注意：这里range(6, 9)是索引的下标，将索引的下标的位置的数据换成-100
print(ser_obj.replace(range(6, 9), -100))
print('-' * 50)

# 将索引的下标4、7位置的数据分别换成-100、-200
print(ser_obj.replace([4, 7], [-100, -200]))

3       0
4    -100
5       2
6       3
7       4
8       5
9       6
10      7
11      8
12      9
dtype: int64
--------------------------------------------------
3       0
4       1
5       2
6       3
7       4
8       5
9    -100
10   -100
11   -100
12      9
dtype: int64
--------------------------------------------------
3       0
4       1
5       2
6       3
7    -100
8       5
9       6
10   -200
11      8
12      9
dtype: int64

In [15]:
df = pd.DataFrame({'A': [0, 1, 2, 3, 4],
                   'B': [5, 6, 7, 8, 9], 
                   'C': ['a', 'b', 'c', 'd', 'e']})
df

   A  B  C
0  0  5  a
1  1  6  b
2  2  7  c
3  3  8  d
4  4  9  e

In [16]:
# 使用正则表达式匹配单元格文本，匹配成功就替换成100
# r'^a'：正则，^代表字符串开头，匹配以字母a开头的字符串
# regex(regular expression)=True：开启正则模式（不加就只是普通字符串匹配，正则符号失效）
df.replace(to_replace=r'^a', value=100, regex=True)

   A  B    C
0  0  5  100
1  1  6    b
2  2  7    c
3  3  8    d
4  4  9    e

In [18]:
df.dtypes

A    int64
B    int64
C      str
dtype: object